version: '3'
services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=Teste
    volumes:
      - ./docker/volume_mysql:/var/lib/mysql
